services:
    redis:
        image: redis:7-alpine
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        environment:
            - REDIS_PASSWORD=dev_password
        command: redis-server --requirepass ${REDIS_PASSWORD}
        profiles:
            - dev

    postgres:
        image: postgres:16-alpine
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=dev_user
            - POSTGRES_PASSWORD=dev_password
            - POSTGRES_DB=app_db
        profiles:
            - dev

volumes:
    redis_data:
        name: redis_data
    postgres_data:
        name: postgres_data
